# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from aegis import aegis_pb2 as aegis_dot_aegis__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class MarkerServiceStub(object):
    """--------------------------------- Marker --------------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Start = channel.unary_unary(
                '/aegis_proto.MarkerService/Start',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/aegis_proto.MarkerService/Stop',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class MarkerServiceServicer(object):
    """--------------------------------- Marker --------------------------------- //

    """

    def Start(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis_proto.MarkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis_proto.MarkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarkerService(object):
    """--------------------------------- Marker --------------------------------- //

    """

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.MarkerService/Start',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.MarkerService/Stop',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RecorderServiceStub(object):
    """--------------------------------- Recorder -------------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListenCommands = channel.unary_stream(
                '/aegis_proto.RecorderService/ListenCommands',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=aegis_dot_aegis__pb2.RecorderCommand.FromString,
                _registered_method=True)


class RecorderServiceServicer(object):
    """--------------------------------- Recorder -------------------------------- //

    """

    def ListenCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecorderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListenCommands': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenCommands,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=aegis_dot_aegis__pb2.RecorderCommand.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis_proto.RecorderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis_proto.RecorderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecorderService(object):
    """--------------------------------- Recorder -------------------------------- //

    """

    @staticmethod
    def ListenCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aegis_proto.RecorderService/ListenCommands',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            aegis_dot_aegis__pb2.RecorderCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObjectServiceStub(object):
    """--------------------------------- Object ---------------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTree = channel.unary_unary(
                '/aegis_proto.ObjectService/GetTree',
                request_serializer=aegis_dot_aegis__pb2.OptionalObject.SerializeToString,
                response_deserializer=aegis_dot_aegis__pb2.ObjectTree.FromString,
                _registered_method=True)
        self.Find = channel.unary_unary(
                '/aegis_proto.ObjectService/Find',
                request_serializer=aegis_dot_aegis__pb2.Object.SerializeToString,
                response_deserializer=aegis_dot_aegis__pb2.Objects.FromString,
                _registered_method=True)
        self.GetParent = channel.unary_unary(
                '/aegis_proto.ObjectService/GetParent',
                request_serializer=aegis_dot_aegis__pb2.Object.SerializeToString,
                response_deserializer=aegis_dot_aegis__pb2.Object.FromString,
                _registered_method=True)
        self.GetChildren = channel.unary_unary(
                '/aegis_proto.ObjectService/GetChildren',
                request_serializer=aegis_dot_aegis__pb2.Object.SerializeToString,
                response_deserializer=aegis_dot_aegis__pb2.Objects.FromString,
                _registered_method=True)
        self.CallMethod = channel.unary_unary(
                '/aegis_proto.ObjectService/CallMethod',
                request_serializer=aegis_dot_aegis__pb2.MethodCall.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.UpdateProperty = channel.unary_unary(
                '/aegis_proto.ObjectService/UpdateProperty',
                request_serializer=aegis_dot_aegis__pb2.PropertyUpdate.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMethods = channel.unary_unary(
                '/aegis_proto.ObjectService/GetMethods',
                request_serializer=aegis_dot_aegis__pb2.Object.SerializeToString,
                response_deserializer=aegis_dot_aegis__pb2.Methods.FromString,
                _registered_method=True)
        self.GetProperties = channel.unary_unary(
                '/aegis_proto.ObjectService/GetProperties',
                request_serializer=aegis_dot_aegis__pb2.Object.SerializeToString,
                response_deserializer=aegis_dot_aegis__pb2.Properties.FromString,
                _registered_method=True)
        self.ListenObjectChanges = channel.unary_stream(
                '/aegis_proto.ObjectService/ListenObjectChanges',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=aegis_dot_aegis__pb2.ObjectChange.FromString,
                _registered_method=True)


class ObjectServiceServicer(object):
    """--------------------------------- Object ---------------------------------- //

    """

    def GetTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Find(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetParent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildren(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallMethod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProperty(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMethods(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProperties(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListenObjectChanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTree,
                    request_deserializer=aegis_dot_aegis__pb2.OptionalObject.FromString,
                    response_serializer=aegis_dot_aegis__pb2.ObjectTree.SerializeToString,
            ),
            'Find': grpc.unary_unary_rpc_method_handler(
                    servicer.Find,
                    request_deserializer=aegis_dot_aegis__pb2.Object.FromString,
                    response_serializer=aegis_dot_aegis__pb2.Objects.SerializeToString,
            ),
            'GetParent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetParent,
                    request_deserializer=aegis_dot_aegis__pb2.Object.FromString,
                    response_serializer=aegis_dot_aegis__pb2.Object.SerializeToString,
            ),
            'GetChildren': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChildren,
                    request_deserializer=aegis_dot_aegis__pb2.Object.FromString,
                    response_serializer=aegis_dot_aegis__pb2.Objects.SerializeToString,
            ),
            'CallMethod': grpc.unary_unary_rpc_method_handler(
                    servicer.CallMethod,
                    request_deserializer=aegis_dot_aegis__pb2.MethodCall.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'UpdateProperty': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProperty,
                    request_deserializer=aegis_dot_aegis__pb2.PropertyUpdate.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMethods': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMethods,
                    request_deserializer=aegis_dot_aegis__pb2.Object.FromString,
                    response_serializer=aegis_dot_aegis__pb2.Methods.SerializeToString,
            ),
            'GetProperties': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProperties,
                    request_deserializer=aegis_dot_aegis__pb2.Object.FromString,
                    response_serializer=aegis_dot_aegis__pb2.Properties.SerializeToString,
            ),
            'ListenObjectChanges': grpc.unary_stream_rpc_method_handler(
                    servicer.ListenObjectChanges,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=aegis_dot_aegis__pb2.ObjectChange.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aegis_proto.ObjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aegis_proto.ObjectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObjectService(object):
    """--------------------------------- Object ---------------------------------- //

    """

    @staticmethod
    def GetTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.ObjectService/GetTree',
            aegis_dot_aegis__pb2.OptionalObject.SerializeToString,
            aegis_dot_aegis__pb2.ObjectTree.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Find(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.ObjectService/Find',
            aegis_dot_aegis__pb2.Object.SerializeToString,
            aegis_dot_aegis__pb2.Objects.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetParent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.ObjectService/GetParent',
            aegis_dot_aegis__pb2.Object.SerializeToString,
            aegis_dot_aegis__pb2.Object.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChildren(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.ObjectService/GetChildren',
            aegis_dot_aegis__pb2.Object.SerializeToString,
            aegis_dot_aegis__pb2.Objects.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallMethod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.ObjectService/CallMethod',
            aegis_dot_aegis__pb2.MethodCall.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProperty(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.ObjectService/UpdateProperty',
            aegis_dot_aegis__pb2.PropertyUpdate.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMethods(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.ObjectService/GetMethods',
            aegis_dot_aegis__pb2.Object.SerializeToString,
            aegis_dot_aegis__pb2.Methods.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProperties(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aegis_proto.ObjectService/GetProperties',
            aegis_dot_aegis__pb2.Object.SerializeToString,
            aegis_dot_aegis__pb2.Properties.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListenObjectChanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/aegis_proto.ObjectService/ListenObjectChanges',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            aegis_dot_aegis__pb2.ObjectChange.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
